env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

defaults:
  run:
    working-directory: terraform

steps:
  - name: Checkout Repository
    uses: actions/checkout@v2

  - name: Set up Terraform
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: 1.5.0

  - name: Terraform Init
    run: terraform init

  - name: Terraform Validate
    run: terraform validate

  - name: Terraform Plan
    run: terraform plan

  - name: Terraform Apply
    run: terraform apply -auto-approve
